// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250630013413_InitialCreateAllTables")]
    partial class InitialCreateAllTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Data.Admin", b =>
                {
                    b.Property<string>("user_id")
                        .HasColumnType("text");

                    b.Property<bool>("is_admin")
                        .HasColumnType("boolean");

                    b.HasKey("user_id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("backend.Data.ApplicationDbContext+Memo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("isdone")
                        .HasColumnType("integer");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("userid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Memos");
                });

            modelBuilder.Entity("backend.Data.ApplicationDbContext+patients", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("address")
                        .HasColumnType("text");

                    b.Property<string>("birth_date")
                        .HasColumnType("text");

                    b.Property<string>("gender")
                        .HasColumnType("text");

                    b.Property<string>("medical_record_no")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("backend.Data.ClinicalData", b =>
                {
                    b.Property<int>("association_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("association_id"));

                    b.Property<string>("disease_stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("specimen_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("symptom_score")
                        .HasColumnType("integer");

                    b.HasKey("association_id");

                    b.ToTable("ClinicalDatas");
                });

            modelBuilder.Entity("backend.Data.Contact", b =>
                {
                    b.Property<string>("contact_id")
                        .HasColumnType("text");

                    b.Property<string>("contact_info")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("patient_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("contact_id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("backend.Data.Diagnosis", b =>
                {
                    b.Property<string>("diagnosis_id")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("disease_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("patient_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("diagnosis_id");

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("backend.Data.FamilyHistory", b =>
                {
                    b.Property<string>("family_history_id")
                        .HasColumnType("text");

                    b.Property<string>("allergy_history")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("patient_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("family_history_id");

                    b.ToTable("FamilyHistories");
                });

            modelBuilder.Entity("backend.Data.FollowUpRecord", b =>
                {
                    b.Property<int>("followup_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("followup_id"));

                    b.Property<int?>("act_score")
                        .HasColumnType("integer");

                    b.Property<string>("adverse_effects")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("followup_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("patient_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("symptom_improvement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("followup_id");

                    b.ToTable("FollowUpRecords");
                });

            modelBuilder.Entity("backend.Data.GenomicData", b =>
                {
                    b.Property<int>("data_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("data_id"));

                    b.Property<DateTime?>("analysis_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("data_path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("il13_genotype")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("il4_genotype")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("specimen_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("data_id");

                    b.ToTable("GenomicDatas");
                });

            modelBuilder.Entity("backend.Data.HouseholdEnvironment", b =>
                {
                    b.Property<string>("household_id")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("bedding_material")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("building_age")
                        .HasColumnType("integer");

                    b.Property<decimal?>("indoor_pm25")
                        .HasColumnType("numeric");

                    b.Property<string>("investigator_id")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("patient_id")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("pet_exposure")
                        .HasColumnType("boolean");

                    b.Property<string>("pet_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("record_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("residence_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ventilation_quality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("household_id");

                    b.HasIndex("investigator_id");

                    b.HasIndex("patient_id");

                    b.ToTable("HouseholdEnvironments");
                });

            modelBuilder.Entity("backend.Data.ImagingDetail", b =>
                {
                    b.Property<string>("imaging_id")
                        .HasColumnType("text");

                    b.Property<string>("exam_details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("lab_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("imaging_id");

                    b.ToTable("ImagingDetails");
                });

            modelBuilder.Entity("backend.Data.IndividualHealthBehavior", b =>
                {
                    b.Property<string>("individual_id")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("antibiotic_usage_frequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("diet_pattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("early_life_medication")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("household_id")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("investigator_id")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("patient_id")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("smoke_exposure")
                        .HasColumnType("boolean");

                    b.Property<bool>("sun_exposure")
                        .HasColumnType("boolean");

                    b.Property<bool>("vaccination_status")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("vitamin_d_level")
                        .HasColumnType("numeric");

                    b.HasKey("individual_id");

                    b.HasIndex("investigator_id");

                    b.HasIndex("patient_id");

                    b.ToTable("IndividualHealthBehaviors");
                });

            modelBuilder.Entity("backend.Data.Insurance", b =>
                {
                    b.Property<string>("insurance_id")
                        .HasColumnType("text");

                    b.Property<string>("insurance_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("patient_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("insurance_id");

                    b.ToTable("Insurance");
                });

            modelBuilder.Entity("backend.Data.InvestigatorQualification", b =>
                {
                    b.Property<string>("investigator_id")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("contact_phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("create_time")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("institution")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("qualification")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("investigator_id");

                    b.ToTable("InvestigatorQualifications");
                });

            modelBuilder.Entity("backend.Data.LabTest", b =>
                {
                    b.Property<string>("lab_id")
                        .HasColumnType("text");

                    b.Property<string>("exam_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("exam_value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("item_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("patient_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("lab_id");

                    b.ToTable("LabTests");
                });

            modelBuilder.Entity("backend.Data.MedicalCost", b =>
                {
                    b.Property<int>("cost_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("cost_id"));

                    b.Property<decimal>("amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("cost_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("cost_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("patient_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("cost_id");

                    b.ToTable("MedicalCosts");
                });

            modelBuilder.Entity("backend.Data.MedicalHistory", b =>
                {
                    b.Property<string>("history_id")
                        .HasColumnType("text");

                    b.Property<string>("allergy_history")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("patient_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("history_id");

                    b.ToTable("MedicalHistories");
                });

            modelBuilder.Entity("backend.Data.MedicationRecord", b =>
                {
                    b.Property<int>("medication_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("medication_id"));

                    b.Property<string>("dosage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("drug_category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("drug_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("frequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("patient_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("medication_id");

                    b.ToTable("MedicationRecords");
                });

            modelBuilder.Entity("backend.Data.PatientBasicInfo", b =>
                {
                    b.Property<string>("patient_id")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("age_at_diagnosi")
                        .HasColumnType("numeric");

                    b.Property<string>("allergy_history")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("birth_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("create_time")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("residence_type")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<DateTime?>("update_time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("patient_id");

                    b.ToTable("PatientBasicInfos");
                });

            modelBuilder.Entity("backend.Data.PatientStaffRelation", b =>
                {
                    b.Property<int>("relation_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("relation_id"));

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("patient_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("relation_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("staff_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("start_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("relation_id");

                    b.ToTable("PatientStaffRelations");
                });

            modelBuilder.Entity("backend.Data.PhysicalExamination", b =>
                {
                    b.Property<int>("exam_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("exam_id"));

                    b.Property<DateTime>("exam_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("lung_sounds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("oxygen_saturation")
                        .HasColumnType("integer");

                    b.Property<string>("patient_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("pulse")
                        .HasColumnType("integer");

                    b.Property<string>("rash_description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("temperature")
                        .HasColumnType("numeric");

                    b.HasKey("exam_id");

                    b.ToTable("PhysicalExaminations");
                });

            modelBuilder.Entity("backend.Data.ProteinData", b =>
                {
                    b.Property<int>("data_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("data_id"));

                    b.Property<DateTime?>("analysis_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("cytokine_profile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("ige_level")
                        .HasColumnType("numeric");

                    b.Property<string>("specimen_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("data_id");

                    b.ToTable("ProteinDatas");
                });

            modelBuilder.Entity("backend.Data.PulmonaryDetail", b =>
                {
                    b.Property<string>("pulmonary_id")
                        .HasColumnType("text");

                    b.Property<string>("exam_details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("lab_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("pulmonary_id");

                    b.ToTable("PulmonaryDetails");
                });

            modelBuilder.Entity("backend.Data.QuestionnaireData", b =>
                {
                    b.Property<string>("questionnaire_id")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("create_time")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("data_source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("fill_date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("form_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("investigator_id")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("patient_id")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("raw_data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("questionnaire_id");

                    b.HasIndex("investigator_id");

                    b.HasIndex("patient_id");

                    b.ToTable("QuestionnaireDatas");
                });

            modelBuilder.Entity("backend.Data.RegionalEnvironment", b =>
                {
                    b.Property<string>("region_id")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("air_quality_index")
                        .HasColumnType("integer");

                    b.Property<decimal?>("avg_temperature")
                        .HasColumnType("numeric");

                    b.Property<string>("climate_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("green_space_rate")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("humidity_level")
                        .HasColumnType("numeric");

                    b.Property<string>("pollen_concentration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("region_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("region_id");

                    b.ToTable("RegionalEnvironments");
                });

            modelBuilder.Entity("backend.Data.SpecimenInfo", b =>
                {
                    b.Property<string>("specimen_id")
                        .HasColumnType("text");

                    b.Property<DateTime>("collection_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("collection_site")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("patient_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("specimen_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("storage_condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("storage_location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("volume_ml")
                        .HasColumnType("numeric");

                    b.HasKey("specimen_id");

                    b.ToTable("SpecimenInfos");
                });

            modelBuilder.Entity("backend.Data.SpecimenQuality", b =>
                {
                    b.Property<int>("quality_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("quality_id"));

                    b.Property<decimal?>("dna_concentration")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("protein_concentration")
                        .HasColumnType("numeric");

                    b.Property<string>("quality_status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("rna_quality")
                        .HasColumnType("numeric");

                    b.Property<string>("specimen_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("quality_id");

                    b.ToTable("SpecimenQualities");
                });

            modelBuilder.Entity("backend.Data.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .HasColumnType("text");

                    b.Property<string>("profession")
                        .HasColumnType("text");

                    b.Property<string>("urlBase64")
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.Data.HouseholdEnvironment", b =>
                {
                    b.HasOne("backend.Data.InvestigatorQualification", "investigator_qualification")
                        .WithMany()
                        .HasForeignKey("investigator_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.PatientBasicInfo", "patient_basic_info")
                        .WithMany()
                        .HasForeignKey("patient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("investigator_qualification");

                    b.Navigation("patient_basic_info");
                });

            modelBuilder.Entity("backend.Data.IndividualHealthBehavior", b =>
                {
                    b.HasOne("backend.Data.InvestigatorQualification", "investigator_qualification")
                        .WithMany()
                        .HasForeignKey("investigator_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.PatientBasicInfo", "patient_basic_info")
                        .WithMany()
                        .HasForeignKey("patient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("investigator_qualification");

                    b.Navigation("patient_basic_info");
                });

            modelBuilder.Entity("backend.Data.QuestionnaireData", b =>
                {
                    b.HasOne("backend.Data.InvestigatorQualification", "investigator_qualification")
                        .WithMany()
                        .HasForeignKey("investigator_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Data.PatientBasicInfo", "patient_basic_info")
                        .WithMany()
                        .HasForeignKey("patient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("investigator_qualification");

                    b.Navigation("patient_basic_info");
                });
#pragma warning restore 612, 618
        }
    }
}
